/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPembayaranRouteImport } from './routes/_authenticated/pembayaran'
import { Route as AuthenticatedLaporanRouteImport } from './routes/_authenticated/laporan'
import { Route as AuthenticatedTagihanIndexRouteImport } from './routes/_authenticated/tagihan.index'
import { Route as AuthenticatedPengaturanIndexRouteImport } from './routes/_authenticated/pengaturan.index'
import { Route as AuthenticatedWhatsappRiwayatRouteImport } from './routes/_authenticated/whatsapp.riwayat'
import { Route as AuthenticatedWhatsappBroadcastRouteImport } from './routes/_authenticated/whatsapp.broadcast'
import { Route as AuthenticatedTagihanIdRouteImport } from './routes/_authenticated/tagihan.$id'
import { Route as AuthenticatedRekapTunggakanRouteImport } from './routes/_authenticated/rekap.tunggakan'
import { Route as AuthenticatedPengaturanPenggunaRouteImport } from './routes/_authenticated/pengaturan.pengguna'
import { Route as AuthenticatedPengaturanAuditRouteImport } from './routes/_authenticated/pengaturan.audit'
import { Route as AuthenticatedMasterTahunAjaranRouteImport } from './routes/_authenticated/master.tahun-ajaran'
import { Route as AuthenticatedMasterSantriRouteImport } from './routes/_authenticated/master.santri'
import { Route as AuthenticatedMasterKelasRouteImport } from './routes/_authenticated/master.kelas'
import { Route as AuthenticatedMasterJenisTagihanRouteImport } from './routes/_authenticated/master.jenis-tagihan'
import { Route as AuthenticatedKwitansiIdRouteImport } from './routes/_authenticated/kwitansi.$id'
import { Route as AuthenticatedRekapSantriIndexRouteImport } from './routes/_authenticated/rekap.santri.index'
import { Route as AuthenticatedRekapSantriIdRouteImport } from './routes/_authenticated/rekap.santri.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPembayaranRoute = AuthenticatedPembayaranRouteImport.update({
  id: '/pembayaran',
  path: '/pembayaran',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLaporanRoute = AuthenticatedLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTagihanIndexRoute =
  AuthenticatedTagihanIndexRouteImport.update({
    id: '/tagihan/',
    path: '/tagihan/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPengaturanIndexRoute =
  AuthenticatedPengaturanIndexRouteImport.update({
    id: '/pengaturan/',
    path: '/pengaturan/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWhatsappRiwayatRoute =
  AuthenticatedWhatsappRiwayatRouteImport.update({
    id: '/whatsapp/riwayat',
    path: '/whatsapp/riwayat',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWhatsappBroadcastRoute =
  AuthenticatedWhatsappBroadcastRouteImport.update({
    id: '/whatsapp/broadcast',
    path: '/whatsapp/broadcast',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTagihanIdRoute = AuthenticatedTagihanIdRouteImport.update({
  id: '/tagihan/$id',
  path: '/tagihan/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRekapTunggakanRoute =
  AuthenticatedRekapTunggakanRouteImport.update({
    id: '/rekap/tunggakan',
    path: '/rekap/tunggakan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPengaturanPenggunaRoute =
  AuthenticatedPengaturanPenggunaRouteImport.update({
    id: '/pengaturan/pengguna',
    path: '/pengaturan/pengguna',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPengaturanAuditRoute =
  AuthenticatedPengaturanAuditRouteImport.update({
    id: '/pengaturan/audit',
    path: '/pengaturan/audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterTahunAjaranRoute =
  AuthenticatedMasterTahunAjaranRouteImport.update({
    id: '/master/tahun-ajaran',
    path: '/master/tahun-ajaran',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterSantriRoute =
  AuthenticatedMasterSantriRouteImport.update({
    id: '/master/santri',
    path: '/master/santri',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterKelasRoute =
  AuthenticatedMasterKelasRouteImport.update({
    id: '/master/kelas',
    path: '/master/kelas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterJenisTagihanRoute =
  AuthenticatedMasterJenisTagihanRouteImport.update({
    id: '/master/jenis-tagihan',
    path: '/master/jenis-tagihan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKwitansiIdRoute = AuthenticatedKwitansiIdRouteImport.update({
  id: '/kwitansi/$id',
  path: '/kwitansi/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRekapSantriIndexRoute =
  AuthenticatedRekapSantriIndexRouteImport.update({
    id: '/rekap/santri/',
    path: '/rekap/santri/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRekapSantriIdRoute =
  AuthenticatedRekapSantriIdRouteImport.update({
    id: '/rekap/santri/$id',
    path: '/rekap/santri/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/laporan': typeof AuthenticatedLaporanRoute
  '/pembayaran': typeof AuthenticatedPembayaranRoute
  '/kwitansi/$id': typeof AuthenticatedKwitansiIdRoute
  '/master/jenis-tagihan': typeof AuthenticatedMasterJenisTagihanRoute
  '/master/kelas': typeof AuthenticatedMasterKelasRoute
  '/master/santri': typeof AuthenticatedMasterSantriRoute
  '/master/tahun-ajaran': typeof AuthenticatedMasterTahunAjaranRoute
  '/pengaturan/audit': typeof AuthenticatedPengaturanAuditRoute
  '/pengaturan/pengguna': typeof AuthenticatedPengaturanPenggunaRoute
  '/rekap/tunggakan': typeof AuthenticatedRekapTunggakanRoute
  '/tagihan/$id': typeof AuthenticatedTagihanIdRoute
  '/whatsapp/broadcast': typeof AuthenticatedWhatsappBroadcastRoute
  '/whatsapp/riwayat': typeof AuthenticatedWhatsappRiwayatRoute
  '/pengaturan/': typeof AuthenticatedPengaturanIndexRoute
  '/tagihan/': typeof AuthenticatedTagihanIndexRoute
  '/rekap/santri/$id': typeof AuthenticatedRekapSantriIdRoute
  '/rekap/santri/': typeof AuthenticatedRekapSantriIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/laporan': typeof AuthenticatedLaporanRoute
  '/pembayaran': typeof AuthenticatedPembayaranRoute
  '/': typeof AuthenticatedIndexRoute
  '/kwitansi/$id': typeof AuthenticatedKwitansiIdRoute
  '/master/jenis-tagihan': typeof AuthenticatedMasterJenisTagihanRoute
  '/master/kelas': typeof AuthenticatedMasterKelasRoute
  '/master/santri': typeof AuthenticatedMasterSantriRoute
  '/master/tahun-ajaran': typeof AuthenticatedMasterTahunAjaranRoute
  '/pengaturan/audit': typeof AuthenticatedPengaturanAuditRoute
  '/pengaturan/pengguna': typeof AuthenticatedPengaturanPenggunaRoute
  '/rekap/tunggakan': typeof AuthenticatedRekapTunggakanRoute
  '/tagihan/$id': typeof AuthenticatedTagihanIdRoute
  '/whatsapp/broadcast': typeof AuthenticatedWhatsappBroadcastRoute
  '/whatsapp/riwayat': typeof AuthenticatedWhatsappRiwayatRoute
  '/pengaturan': typeof AuthenticatedPengaturanIndexRoute
  '/tagihan': typeof AuthenticatedTagihanIndexRoute
  '/rekap/santri/$id': typeof AuthenticatedRekapSantriIdRoute
  '/rekap/santri': typeof AuthenticatedRekapSantriIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/laporan': typeof AuthenticatedLaporanRoute
  '/_authenticated/pembayaran': typeof AuthenticatedPembayaranRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/kwitansi/$id': typeof AuthenticatedKwitansiIdRoute
  '/_authenticated/master/jenis-tagihan': typeof AuthenticatedMasterJenisTagihanRoute
  '/_authenticated/master/kelas': typeof AuthenticatedMasterKelasRoute
  '/_authenticated/master/santri': typeof AuthenticatedMasterSantriRoute
  '/_authenticated/master/tahun-ajaran': typeof AuthenticatedMasterTahunAjaranRoute
  '/_authenticated/pengaturan/audit': typeof AuthenticatedPengaturanAuditRoute
  '/_authenticated/pengaturan/pengguna': typeof AuthenticatedPengaturanPenggunaRoute
  '/_authenticated/rekap/tunggakan': typeof AuthenticatedRekapTunggakanRoute
  '/_authenticated/tagihan/$id': typeof AuthenticatedTagihanIdRoute
  '/_authenticated/whatsapp/broadcast': typeof AuthenticatedWhatsappBroadcastRoute
  '/_authenticated/whatsapp/riwayat': typeof AuthenticatedWhatsappRiwayatRoute
  '/_authenticated/pengaturan/': typeof AuthenticatedPengaturanIndexRoute
  '/_authenticated/tagihan/': typeof AuthenticatedTagihanIndexRoute
  '/_authenticated/rekap/santri/$id': typeof AuthenticatedRekapSantriIdRoute
  '/_authenticated/rekap/santri/': typeof AuthenticatedRekapSantriIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/laporan'
    | '/pembayaran'
    | '/kwitansi/$id'
    | '/master/jenis-tagihan'
    | '/master/kelas'
    | '/master/santri'
    | '/master/tahun-ajaran'
    | '/pengaturan/audit'
    | '/pengaturan/pengguna'
    | '/rekap/tunggakan'
    | '/tagihan/$id'
    | '/whatsapp/broadcast'
    | '/whatsapp/riwayat'
    | '/pengaturan/'
    | '/tagihan/'
    | '/rekap/santri/$id'
    | '/rekap/santri/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/laporan'
    | '/pembayaran'
    | '/'
    | '/kwitansi/$id'
    | '/master/jenis-tagihan'
    | '/master/kelas'
    | '/master/santri'
    | '/master/tahun-ajaran'
    | '/pengaturan/audit'
    | '/pengaturan/pengguna'
    | '/rekap/tunggakan'
    | '/tagihan/$id'
    | '/whatsapp/broadcast'
    | '/whatsapp/riwayat'
    | '/pengaturan'
    | '/tagihan'
    | '/rekap/santri/$id'
    | '/rekap/santri'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/laporan'
    | '/_authenticated/pembayaran'
    | '/_authenticated/'
    | '/_authenticated/kwitansi/$id'
    | '/_authenticated/master/jenis-tagihan'
    | '/_authenticated/master/kelas'
    | '/_authenticated/master/santri'
    | '/_authenticated/master/tahun-ajaran'
    | '/_authenticated/pengaturan/audit'
    | '/_authenticated/pengaturan/pengguna'
    | '/_authenticated/rekap/tunggakan'
    | '/_authenticated/tagihan/$id'
    | '/_authenticated/whatsapp/broadcast'
    | '/_authenticated/whatsapp/riwayat'
    | '/_authenticated/pengaturan/'
    | '/_authenticated/tagihan/'
    | '/_authenticated/rekap/santri/$id'
    | '/_authenticated/rekap/santri/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pembayaran': {
      id: '/_authenticated/pembayaran'
      path: '/pembayaran'
      fullPath: '/pembayaran'
      preLoaderRoute: typeof AuthenticatedPembayaranRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/laporan': {
      id: '/_authenticated/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof AuthenticatedLaporanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tagihan/': {
      id: '/_authenticated/tagihan/'
      path: '/tagihan'
      fullPath: '/tagihan/'
      preLoaderRoute: typeof AuthenticatedTagihanIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengaturan/': {
      id: '/_authenticated/pengaturan/'
      path: '/pengaturan'
      fullPath: '/pengaturan/'
      preLoaderRoute: typeof AuthenticatedPengaturanIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp/riwayat': {
      id: '/_authenticated/whatsapp/riwayat'
      path: '/whatsapp/riwayat'
      fullPath: '/whatsapp/riwayat'
      preLoaderRoute: typeof AuthenticatedWhatsappRiwayatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp/broadcast': {
      id: '/_authenticated/whatsapp/broadcast'
      path: '/whatsapp/broadcast'
      fullPath: '/whatsapp/broadcast'
      preLoaderRoute: typeof AuthenticatedWhatsappBroadcastRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tagihan/$id': {
      id: '/_authenticated/tagihan/$id'
      path: '/tagihan/$id'
      fullPath: '/tagihan/$id'
      preLoaderRoute: typeof AuthenticatedTagihanIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rekap/tunggakan': {
      id: '/_authenticated/rekap/tunggakan'
      path: '/rekap/tunggakan'
      fullPath: '/rekap/tunggakan'
      preLoaderRoute: typeof AuthenticatedRekapTunggakanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengaturan/pengguna': {
      id: '/_authenticated/pengaturan/pengguna'
      path: '/pengaturan/pengguna'
      fullPath: '/pengaturan/pengguna'
      preLoaderRoute: typeof AuthenticatedPengaturanPenggunaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengaturan/audit': {
      id: '/_authenticated/pengaturan/audit'
      path: '/pengaturan/audit'
      fullPath: '/pengaturan/audit'
      preLoaderRoute: typeof AuthenticatedPengaturanAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master/tahun-ajaran': {
      id: '/_authenticated/master/tahun-ajaran'
      path: '/master/tahun-ajaran'
      fullPath: '/master/tahun-ajaran'
      preLoaderRoute: typeof AuthenticatedMasterTahunAjaranRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master/santri': {
      id: '/_authenticated/master/santri'
      path: '/master/santri'
      fullPath: '/master/santri'
      preLoaderRoute: typeof AuthenticatedMasterSantriRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master/kelas': {
      id: '/_authenticated/master/kelas'
      path: '/master/kelas'
      fullPath: '/master/kelas'
      preLoaderRoute: typeof AuthenticatedMasterKelasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master/jenis-tagihan': {
      id: '/_authenticated/master/jenis-tagihan'
      path: '/master/jenis-tagihan'
      fullPath: '/master/jenis-tagihan'
      preLoaderRoute: typeof AuthenticatedMasterJenisTagihanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kwitansi/$id': {
      id: '/_authenticated/kwitansi/$id'
      path: '/kwitansi/$id'
      fullPath: '/kwitansi/$id'
      preLoaderRoute: typeof AuthenticatedKwitansiIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rekap/santri/': {
      id: '/_authenticated/rekap/santri/'
      path: '/rekap/santri'
      fullPath: '/rekap/santri/'
      preLoaderRoute: typeof AuthenticatedRekapSantriIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rekap/santri/$id': {
      id: '/_authenticated/rekap/santri/$id'
      path: '/rekap/santri/$id'
      fullPath: '/rekap/santri/$id'
      preLoaderRoute: typeof AuthenticatedRekapSantriIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedLaporanRoute: typeof AuthenticatedLaporanRoute
  AuthenticatedPembayaranRoute: typeof AuthenticatedPembayaranRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedKwitansiIdRoute: typeof AuthenticatedKwitansiIdRoute
  AuthenticatedMasterJenisTagihanRoute: typeof AuthenticatedMasterJenisTagihanRoute
  AuthenticatedMasterKelasRoute: typeof AuthenticatedMasterKelasRoute
  AuthenticatedMasterSantriRoute: typeof AuthenticatedMasterSantriRoute
  AuthenticatedMasterTahunAjaranRoute: typeof AuthenticatedMasterTahunAjaranRoute
  AuthenticatedPengaturanAuditRoute: typeof AuthenticatedPengaturanAuditRoute
  AuthenticatedPengaturanPenggunaRoute: typeof AuthenticatedPengaturanPenggunaRoute
  AuthenticatedRekapTunggakanRoute: typeof AuthenticatedRekapTunggakanRoute
  AuthenticatedTagihanIdRoute: typeof AuthenticatedTagihanIdRoute
  AuthenticatedWhatsappBroadcastRoute: typeof AuthenticatedWhatsappBroadcastRoute
  AuthenticatedWhatsappRiwayatRoute: typeof AuthenticatedWhatsappRiwayatRoute
  AuthenticatedPengaturanIndexRoute: typeof AuthenticatedPengaturanIndexRoute
  AuthenticatedTagihanIndexRoute: typeof AuthenticatedTagihanIndexRoute
  AuthenticatedRekapSantriIdRoute: typeof AuthenticatedRekapSantriIdRoute
  AuthenticatedRekapSantriIndexRoute: typeof AuthenticatedRekapSantriIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedLaporanRoute: AuthenticatedLaporanRoute,
  AuthenticatedPembayaranRoute: AuthenticatedPembayaranRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedKwitansiIdRoute: AuthenticatedKwitansiIdRoute,
  AuthenticatedMasterJenisTagihanRoute: AuthenticatedMasterJenisTagihanRoute,
  AuthenticatedMasterKelasRoute: AuthenticatedMasterKelasRoute,
  AuthenticatedMasterSantriRoute: AuthenticatedMasterSantriRoute,
  AuthenticatedMasterTahunAjaranRoute: AuthenticatedMasterTahunAjaranRoute,
  AuthenticatedPengaturanAuditRoute: AuthenticatedPengaturanAuditRoute,
  AuthenticatedPengaturanPenggunaRoute: AuthenticatedPengaturanPenggunaRoute,
  AuthenticatedRekapTunggakanRoute: AuthenticatedRekapTunggakanRoute,
  AuthenticatedTagihanIdRoute: AuthenticatedTagihanIdRoute,
  AuthenticatedWhatsappBroadcastRoute: AuthenticatedWhatsappBroadcastRoute,
  AuthenticatedWhatsappRiwayatRoute: AuthenticatedWhatsappRiwayatRoute,
  AuthenticatedPengaturanIndexRoute: AuthenticatedPengaturanIndexRoute,
  AuthenticatedTagihanIndexRoute: AuthenticatedTagihanIndexRoute,
  AuthenticatedRekapSantriIdRoute: AuthenticatedRekapSantriIdRoute,
  AuthenticatedRekapSantriIndexRoute: AuthenticatedRekapSantriIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
